### ISSUE TITLE
Adding a link to the commit

### ISSUE THREAD

**Issue by M4GNV5** [sameetandpotatoes/callouscommits#1]
Imo the tweet should contain the url of the commit on github so people that are interrested in who actually wrote those **bad bad words** can find them muhahahahahah :laughing:

**Comment by sameetandpotatoes** [comment]
I considered doing this awhile ago, but I wasn't sure if developers might find this a bit embarrassing. I decided to add this feature back in. Instead of linking to the commit, I decided to link to their GitHub profile, as that might be more interesting for others to see. Thanks for your input :)
