### ISSUE TITLE
Filter @ at the beginning of a tweet

### ISSUE THREAD

**Issue by WebFreak001** [sameetandpotatoes/callouscommits#2]
When starting a commit with an @ the tweet will mention that person. That could be annoying if that person is someone completely different. Putting " around the quote could work and also the tweets are not visible on your profile page or in the followers time line unless you click Tweets & Replies

**Comment by sameetandpotatoes** [comment]
Is this in reference to one of my other twitter bots, such as my Illuminati Bot? I'm sorry, but I'm not sure I understand your suggestions. What do you mean by 'putting " around the quote'? Also, I understand that my tweets are not visible until I click "Tweets and Replies", but when visiting my profile page when I am not logged in under that account, I do, in fact, see all of the tweets right away without clicking on "Tweets & Replies". You can see that too [here](https://twitter.com/illuminatius3).

**Comment by WebFreak001** [comment]
yeah but people following callouscommit won't see these tweets. Or you could use the way other people do it to make a tweet to someone public: just put a dot (.) before the @ if it starts with an @

**Comment by sameetandpotatoes** [comment]
Oh, I see. I had no idea about this. I added a '.' before the @ in the tweet, and now it does show up under Tweets. Thank you for pointing that out!
